---
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: chef_zero

platforms:
  - name: debian-8.2

suites:
  - name: default
    run_list:
      - recipe[site-ldaptypo3org::default]
    attributes:
      openldap:
        rootpw: "{SSHA}6BjlvtSbVCL88li8IorkqMSofkLio58/" #secretsauce
      site-ldaptypo3org:
        ssl_certificate: wildcard.vagrant
    driver_config:
      network:
      - ["private_network", {ip: "192.168.88.24"}]
